include ~/.cache/wal/colors-kitty.conf

font_size 20.0
font_family JetBrains Mono Nerd Font

background_blur 25
background_opacity 0.90
copy_on_select yes
allow_hyperlinks yes

# Keybindings

## Potentially changing it to alt+shift?
kitty_mod ctrl+shift

map ctrl+shift+v paste_from_clipboard

## Terminal Splitting
map kitty_mod+enter new_window
map ctrl+f launch --location=neighbor

## Getting used to Vim motions, so...
map kitty_mod+j next_window
map kitty_mod+k previous_window