###################
###  Variables  ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = sherlock toggle
# $menu = sherlock
$browser = zen-browser
$screenshot = grimblast --notify copysave area ~/Pictures/Screenshots/$(date +%F_%T).png
$restartBar = killall waybar && waybar
$editor = dunstify "Opening Zed..."  -u low -t 2000 -r 1004 -i zed && ~/.local/bin/zed

## Custom made scripts :D
$wallSwitch = ~/.config/hypr/scripts/change_wall.sh
$pywallSwitch = ~/.config/hypr/scripts/change_pywal.sh
$runObsidian = ~/.config/hypr/scripts/run_obsidian.sh
