# Taran's simple simple Starship.rs config :D

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# format = "$python[➜](bold green) $directory($git_branch)"

command_timeout = 1000

[directory]
truncation_length = 1

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

